// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ05efQCRtJ3er1YZzbooH_ZznCIZwgwc',
    appId: '1:798235182933:web:57a0c6ff918ed4946151dc',
    messagingSenderId: '798235182933',
    projectId: 'vibration-bts',
    authDomain: 'vibration-bts.firebaseapp.com',
    storageBucket: 'vibration-bts.firebasestorage.app',
    measurementId: 'G-XKC3QEWFR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIRcy9ZHeDqWYonYbvB4dU66Iy9xJ7P-M',
    appId: '1:798235182933:android:2a7b818efc5115376151dc',
    messagingSenderId: '798235182933',
    projectId: 'vibration-bts',
    storageBucket: 'vibration-bts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1DGMnlRykSZoE_nf2H2EZMFH-JxVFmX4',
    appId: '1:798235182933:ios:390ed66baca1d2926151dc',
    messagingSenderId: '798235182933',
    projectId: 'vibration-bts',
    storageBucket: 'vibration-bts.firebasestorage.app',
    iosBundleId: 'com.example.projectVa1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1DGMnlRykSZoE_nf2H2EZMFH-JxVFmX4',
    appId: '1:798235182933:ios:390ed66baca1d2926151dc',
    messagingSenderId: '798235182933',
    projectId: 'vibration-bts',
    storageBucket: 'vibration-bts.firebasestorage.app',
    iosBundleId: 'com.example.projectVa1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ05efQCRtJ3er1YZzbooH_ZznCIZwgwc',
    appId: '1:798235182933:web:8759dda6a51ea5a76151dc',
    messagingSenderId: '798235182933',
    projectId: 'vibration-bts',
    authDomain: 'vibration-bts.firebaseapp.com',
    storageBucket: 'vibration-bts.firebasestorage.app',
    measurementId: 'G-HK6FLH21R3',
  );

}